import { Works, WorkCategory, Technology } from "../data/works";

/**
 * 画像の存在を確認する関数
 */
const checkImageExists = (src: string): Promise<boolean> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(true);
    img.onerror = () => resolve(false);
    img.src = src;
  });
};

/**
 * public/images/works内の連番フォルダを検出する関数
 * サムネイル画像の存在を確認して、有効なフォルダを判定
 */
export async function detectWorksFolders(
  maxId: number = 20
): Promise<number[]> {
  const detectedFolders: number[] = [];
  const checkPromises: Promise<boolean>[] = [];

  // 1からmaxIdまで順番にチェック
  for (let id = 1; id <= maxId; id++) {
    const thumbnailPath = `/images/works/${id}/thumbnail.webp`;
    checkPromises.push(
      checkImageExists(thumbnailPath).then((exists) => {
        if (exists) {
          detectedFolders.push(id);
        }
        return exists;
      })
    );
  }

  // 並列で画像の存在を確認
  await Promise.all(checkPromises);

  // 数値順にソート
  return detectedFolders.sort((a, b) => a - b);
}

/**
 * デフォルトのworksデータを生成する関数
 */
export function generateDefaultWorkData(id: number): Works {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = String(currentDate.getMonth() + 1).padStart(2, "0");
  const dateString = `${year}.${month}`;

  return {
    id,
    title: `作品 ${id}`,
    date: dateString,
    role: "開発・デザイン",
    client: "クライアント名",
    industry: "その他",
    technologies: ["HTML", "CSS", "JavaScript"] as Technology[],
    category: ["サービスサイト"] as WorkCategory[],
    details: {
      overview: ["作品の概要をここに記入してください。"],
      challenge: ["課題をここに記入してください。"],
      solution: ["解決策をここに記入してください。"],
      result: ["成果をここに記入してください。"],
      features: ["主な機能をここに記入してください。"],
      link: "",
    },
    mediaData: {
      images: [],
      videos: [],
    },
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

/**
 * 既存のworksデータと自動生成データをマージする関数
 * 既存データを優先し、存在しないIDのみ自動生成データを追加
 */
export function mergeWorksData(
  existingWorks: Works[],
  autoGeneratedWorks: Works[]
): Works[] {
  const existingIds = new Set(existingWorks.map((work) => work.id));
  const newWorks = autoGeneratedWorks.filter(
    (work) => !existingIds.has(work.id)
  );

  // 既存データと新規データをマージ（既存データを優先）
  return [...existingWorks, ...newWorks].sort((a, b) => a.id - b.id);
}

/**
 * フォルダから自動的にworksデータを生成する関数
 */
export async function autoGenerateWorksData(
  existingWorks: Works[]
): Promise<Works[]> {
  console.log("🔍 worksフォルダを自動検出中...");

  // フォルダを検出
  const detectedFolders = await detectWorksFolders(20);
  console.log(
    `✅ ${detectedFolders.length}個のworksフォルダを検出しました:`,
    detectedFolders
  );

  if (detectedFolders.length === 0) {
    console.log("⚠️ worksフォルダが見つかりませんでした");
    return existingWorks;
  }

  // 既存のIDを取得
  const existingIds = new Set(existingWorks.map((work) => work.id));

  // 検出されたフォルダから、既存データにないIDのworksデータを生成
  const newWorks: Works[] = [];
  for (const id of detectedFolders) {
    if (!existingIds.has(id)) {
      const defaultWork = generateDefaultWorkData(id);
      newWorks.push(defaultWork);
      console.log(`📝 新規worksデータを生成しました: ID ${id}`);
    }
  }

  if (newWorks.length === 0) {
    console.log("ℹ️ 新規のworksデータはありませんでした");
    return existingWorks;
  }

  // 既存データとマージ
  const mergedWorks = mergeWorksData(existingWorks, newWorks);
  console.log(
    `✅ worksデータをマージしました: 合計 ${mergedWorks.length}件`
  );

  return mergedWorks;
}

